version: '3.8'

services:
  flutter:
    build:
      context: .
      dockerfile: Dockerfile
    image: d4rt-formulas-builder
    volumes:
      - ./.build-container-cache:/cache:z
      - .:/app:z  # Link the current directory to /app in the container
    environment:
      - FLUTTER_FLAVOR=prod  # Example environment variable, adjust as needed
