name: d4rt_formulas
description: A command-line application for executing formulas using the d4rt interpreter.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 3.8.1
  flutter: 3.32.4

# Add regular dependencies here.
dependencies:

  # path: ^1.8.0
  d4rt: 
ema
dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
