name: Create release from tag

on:
  push:
    tags:
      - 'release-*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # needed to create releases
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Environment Variables
        run: env

      - name: Make
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./release.sh
